### ISSUE TITLE
RightCurlyCheck.isBlockAloneOnSingleLine might throw NPE 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11054]
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AXf41WU2KOH-lPjDUOPU&open=AXf41WU2KOH-lPjDUOPU

disabled in Sonar until this issue, so remove Wontfix in Sonar after fix.

![image](https://user-images.githubusercontent.com/812984/146663280-aff33281-d73c-4e54-beda-d9244c152600.png)

**Comment by nmancus1** [comment]
We could resolve all such issues in https://github.com/checkstyle/checkstyle/issues/10557

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/9456a052d88382854b60877fd9959318b3d87296/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L464

There are no exceptions being generated in regression. These properties were not part of our standard regression.
http://rveach.no-ip.org/checkstyle/regression/300/

Unless there is some very special input file needed, I don't believe there is a way we can cover pitest with a change like this. I feel with have to be very careful with "Exception could be thrown". I feel it just says extra noise on code that looks like it could be possibly but can't fully understand the application to know if it IS possible or not.

**Comment by rnveach** [comment]
After doing an analysis, this is what is needed for an exception here.

At https://github.com/checkstyle/checkstyle/blob/9456a052d88382854b60877fd9959318b3d87296/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L464
* nextToken must be `null`
* `details.nextToken` cannnot be `null` as we have a `null` check, so `Details.getNextToken` has to return `null` after `nextToken` is an `ELSE`.
https://github.com/checkstyle/checkstyle/blob/9456a052d88382854b60877fd9959318b3d87296/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L714
* `Details.getNextToken` only returns `null` when the token passed to it is `null` or the next sibling of the node passed to it is `null`.

Since what we pass to `Details.getNextToken` has to be `ELSE`, we can never have it return `null` since we would run into the `OBJBLOCK`'s `RCURLY` and the `CLASS_DEF`'s `RCURLY`.

The only way I see to satisfy this is somehow to rewrite the code or add another null check that will never satisfy pitest.

**Comment by rnveach** [comment]
As for a rewrite, the best I can see is:

````
        while (nextToken != null && nextToken.getType() == TokenTypes.LITERAL_ELSE) {
            nextToken = Details.getNextToken(nextToken);
        }

        if (nextToken != null) {
            if (nextToken.getType() == TokenTypes.DO_WHILE) {
                final DetailAST doWhileSemi = nextToken.getParent().getLastChild();
                nextToken = Details.getNextToken(doWhileSemi);
            }
        }
````

**Comment by strkkk** [comment]
fix is merged, @romani please adjust sonar

**Comment by romani** [comment]
![image](https://user-images.githubusercontent.com/812984/146826571-133914c8-5fe1-43a6-98de-4acc44ef6c7d.png)

Wontfix changed to reopened.

**Comment by romani** [comment]
wercker is green, violation still shown in Sonar. 
now I marked it as "resolved".
restarting wercker.

**Comment by romani** [comment]
Sonar is clean now.
