### ISSUE TITLE
Remove branch filter `pitest` from Team City config

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#11772]
Added to avoid execution of Team City inspections in pitest mutation killing PRs, we need to remove this filter after GSOC is complete.

I am not sure if we are able to set branch filters in text based Project config, but if so, we can resolve this issue when we come to this stage, since we will be done with pitest. Right now the branch filter is set in admin area of web UI.

We have ended up adding a filter by username as well:
![image](https://user-images.githubusercontent.com/31252532/176888603-ea27516c-9522-49b2-95b7-9dd834274c7f.png)

We will need to remove this filter as well.

**Comment by Vyom-Yadav** [comment]
TeamCity inspections ran in both #11770 and #11771. Both PRs had names ending with `pitest`.
See https://teamcity.jetbrains.com/viewLog.html?buildId=3880029&buildTypeId=Checkstyle_IdeaInspectionsPullRequest and https://teamcity.jetbrains.com/viewLog.html?buildId=3880028&buildTypeId=Checkstyle_IdeaInspectionsPullRequest

**Comment by nick-mancuso** [comment]
@Vyom-Yadav I have updated branch filters, let’s try again.

**Comment by romani** [comment]
@nick-mancuso , please share how filter shuold  looks like. I thought I did this yesterday. Need to know where was mistake.

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav I have updated branch filters, let’s try again.

It's still not working, see https://github.com/checkstyle/checkstyle/pull/11778 and other latest draft PRs.

**Comment by nick-mancuso** [comment]
> > @Vyom-Yadav I have updated branch filters, let’s try again.
> 
> It's still not working, see #11778 and other latest draft PRs.

Ok, updated again, I feel confident about this one.

**Comment by nick-mancuso** [comment]
> please share how filter shuold looks like. I thought I did this yesterday. Need to know where was mistake.


![Screenshot from 2022-06-27 07-30-43](https://user-images.githubusercontent.com/31252532/175931748-bdb91bee-bbcd-4670-bf7d-82108823575a.png)

**Comment by nick-mancuso** [comment]
Ok, we have updated online config to filter by commit message:
![image](https://user-images.githubusercontent.com/31252532/177005393-06f8ccc0-dce4-4144-a5de-e74a8fb9bd93.png)

@Vyom-Yadav So we should use `minor: skip TC` as commit message to skip.

@romani I am good to keep this branch filter forever, as we have kept disabled CI branch in main project as well. If you agree, let's close this issue. I have removed other branch filters associated with main issue description.

**Comment by romani** [comment]
I think first section of VCS rules are outdated.
I tried by such rules to reduce execution of TC , if we change unrelated files.
But right now TC is validating not only java files, so all such files are under TC validation, so better to run always.

**Comment by Vyom-Yadav** [comment]
Can we close this @romani @nrmancuso ?

**Comment by romani** [comment]
No filters right now https://teamcity.jetbrains.com/admin/editTriggers.html?id=buildType:Checkstyle_IdeaInspectionsMaster
