### ISSUE TITLE
resolve IDEA inspection BooleanParameter in AbstractModuleTestSupport.createChecker

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4857]
hot fix - https://github.com/checkstyle/checkstyle/commit/1b7f820e208e9aa3bfb8211b0db64735baf6d4b9

need to be resolved.

@Nimfadora , please take a look.

**Comment by romani** [comment]
fix is merged

**Comment by rnveach** [comment]
@romani Look at comment https://github.com/checkstyle/checkstyle/issues/4857#issuecomment-319644435 , `IT` area was not fixed yet.

**Comment by romani** [comment]
@Nimfadora , please resolve issue in IT area.
