### ISSUE TITLE
Add (WS | NEWLINE) in proper places for javadoc tags

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4934]
$ cat test.javadoc
```
* @exception Exception-javadoc-description
```

$ java -jar master-8.2-all.jar -j test.javadoc 

```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--WS ->   [0:1]
|--JAVADOC_TAG -> JAVADOC_TAG [0:2]
|   |--EXCEPTION_LITERAL -> @exception [0:2]
|   |--WS ->   [0:12]
|   |--CLASS_NAME -> Exception [0:13]
|   `--DESCRIPTION -> DESCRIPTION [0:22]
|       |--TEXT -> **-javadoc-description** [0:22]
|       `--NEWLINE -> \n [0:42]
`--EOF -> <EOF> [1:0]
```

As can be seen the tree doesn't seem correct and `WS` should be enforced before description as even the [syntax for `@exception` in oracle docs](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#exception) suggests.

**Another example:**

$ cat test.javadoc 
```
* @param Exception-javadoc-description
```

$ java -jar master-8.2-all.jar -j test.javadoc
```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--WS ->   [0:1]
|--JAVADOC_TAG -> JAVADOC_TAG [0:2]
|   |--PARAM_LITERAL -> @param [0:2]
|   |--WS ->   [0:8]
|   |--PARAMETER_NAME -> Exception [0:9]
|   `--DESCRIPTION -> DESCRIPTION [0:18]
|       |--TEXT -> **-javadoc-description** [0:18]
|       `--NEWLINE -> \n [0:38]
`--EOF -> <EOF> [1:0]
```

So `WS` should be added in all the right places for javadoc tags based on their syntax in [oracle docs](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html).

**Comment by romani** [comment]
fix is merged

**Comment by ps-sp** [comment]
@romani Issue is not fixed yet. That PR just concerned with all block javadoc tags except `@see`. Please reopen

**Comment by romani** [comment]
fix is merged
