### ISSUE TITLE
Update AbstractChecks to log DetailAST - UnnecessaryParentheses

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7765]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on UnnecessaryParentheses.

**Comment by yajna-pandith** [comment]
I am on it

**Comment by yajna-pandith** [comment]
I am on it

**Comment by AnishaSrivastava1411** [comment]
@yajna-pandith Are you still working on this?

**Comment by AnishaSrivastava1411** [comment]
@rnveach  Please assign the issue to me.

**Comment by yajna-pandith** [comment]
It has already been solved .

**Comment by AnishaSrivastava1411** [comment]
Hi @yajna-pandith ,
I think you have mislabeled me or you want Anirvan Sarkar to work on  the issue?

**Comment by yajna-pandith** [comment]
My bad @AnishaSrivastava1411 . Go ahead but i think it is already solved . The below is the master branch with "ast" at all the appropriate places.
![UnnecessaryParantheses](https://user-images.githubusercontent.com/25138248/77196724-eb9c7b00-6b09-11ea-9ae1-0103d0053174.png)

**Comment by rnveach** [comment]
Issue is not resolved as there are no xpath tests to provide logging by AST is working.
See https://github.com/checkstyle/checkstyle/blob/53cddfd752c5a6b410a652ffb2bce2d9f6ff14ab/src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java#L82

**Comment by shashwat70** [comment]
Claiming this since there's no activity since almost a month.
I'm on it! :)

**Comment by romani** [comment]
fix is merged.
