### ISSUE TITLE
Would it be possible to support non-ASCII characters in identifiers?

### ISSUE THREAD

**Issue by blerner** [checkstyle/checkstyle#8050]
According to [Checkstyle's limitations](https://checkstyle.org/writingchecks.html#Limitations), checkstyle does not support UTF-8 characters, and indeed [the grammar](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocLexer.g4#L267-L269) defines an overly simple regex for recognizing identifiers.  But it's not quite true that checkstyle doesn't support _any_ UTF-8 though, since UTF-8 characters in strings or comments are matched by the `.` regex and are therefore silently accepted.

Per [the JLS, section 3.8](https://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.8), identifiers are richer than the simple `[A-Za-z_$][0-9A-Za-z_$]*` regex defined in JavadocLexer.g4.  I think a closer regex that's compatible with Antlr's [Lexer rule elements](https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#lexer-rule-elements) would be

```
fragment JavaIdentStart: [\p{N}\p{L}\p{Sc}\p{Pc}];
fragment JavaIdentPart: [\p{N}\p{L}\p{Sc}\p{Pc}\p{M}];
fragment Identifier: JavaIdentStart (JavaIdentPart)*;
```

I see that there are prior issues similar to this (mainly #4562), but I guess my question is, if it's technically feasible and not too difficult to fix the definition of `Identifier` above to be more faithful to the JLS, why should this limitation continue?  If this is simply a hard rule that checkstyle insists upon, feel free to close this issue as a duplicate, but it seems like an odd inconsistency to enforce.

**Comment by romani** [comment]
I do believe it is feasible but very hard, we put it in limitation as we do not see much value for it in comparison to all other features. 
But if somebody have time to invest into this ... sure, lets do something. BUT we will not merge "something" it has to pass same quality gate as all other features.

**Comment by harsh-kukreja** [comment]
Hey @romani this feature is supported in antlr4 right? But our java grammar is still on antlr2 so can you give me some hint on how should we approach

**Comment by blerner** [comment]
Certainly, I'm not advocating doing "something" without checking that it works!  Indeed, I'm trying to be particularly cautious, and suggested only a tiny change that seemed to be minimally invasive.  I've downloaded checkstyle, built it, ran the test suite (via Maven -> test in IntelliJ; I'm assuming that's the correct way to run the full test suite) to confirm everything passes in a clean state, made just the 3-line change above, and ran the test suite again -- and everything still passes.  So the suggestion above introduces no regressions.

I tried modifying the [InputUppercaseInPackageName.javadoc](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/javadocTags/InputUppercaseInPackageName.javadoc) test to include non-ASCII characters, and that failed: my changes to the lexer were too narrow.  But examining [JLS chapter 18](https://docs.oracle.com/javase/specs/jls/se7/html/jls-18.html) and the lexer some more, I changed `MEMBER`, `ARGUMENT`, `FIELD_NAME`, `FIELD_TYPE` and `CLASS_NAME` (basically, every place that had a use of `a-zA-Z` in a regex that was used for Java names; I didn't touch anything relating to HTML markup) to all use `Identifier`, and that test now works.

Are there other tests I should try to confirm that recognizing non-ASCII characters works as intended?  Are there other pitfalls I am not aware of?  I'm a user of checkstyle, not an expert developer of it, so I'm trying to understand rather than suggest infeasible or impractical changes.

**Comment by romani** [comment]
We need to write bunch of test inputs in different languages. It will be very hard to find open source project in non- English, I have never seen such code in my life, so testing should be thought.
We need to make AST regression report to make sure there is no chance in tree.

**Comment by blerner** [comment]
It seems like a fuzz-based approach here might work well: extract a bunch of test cases from e.g. [Eclipse's Java parser tests](https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler), and naively mutate them by substituting anything that matched the original `[a-zA-Z0-9$_]`-based regexs with a few different non-ASCII strings, and see if it still parses.  (My student tried using `DéjàVu` in a method name; I've seen examples online where names are in Cyrillic or other non-Latin scripts; but I don't believe that emoji are legal Java identifier names...yet!)

**Comment by nmancus1** [comment]
After https://github.com/checkstyle/checkstyle/pull/10280, we are able to handle any valid java identifier. Relevant lexer rule:

```antlr

fragment Letter
    // these are the "java letters" below 0x7F
    : [a-zA-Z$_]
    // covers all characters above 0x7F which are not a surrogate
    | ~[\u0000-\u007F\uD800-\uDBFF]
    // covers UTF-16 surrogate pairs encodings for U+10000 to U+10FFFF
    | [\uD800-\uDBFF] [\uDC00-\uDFFF]
    ;

```

To show that we are able to parse all valid java identifiers, I can make a test case using ALL valid java identifier characters in variable declarations.

**Comment by rnveach** [comment]
Fix was merged

**Comment by nmancus1** [comment]
We need to revisit this issue

While our ANTLR4 Java grammar now supports unicode characters, our ANTLR4 Javadoc grammar still does not:

```bash

 ➜  src cat Test.java                                         
public class Test {

    /**
     *
     * @param ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ
     */
    void aᇭᇮᇯᇰᇱᇲᇳᇴᇵᇶᇷᇸᇹᇺ(int ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ) {}


}

 ➜  src java -jar checkstyle-9.0-SNAPSHOT-all.jar -T Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> Test [1:13]
`--OBJBLOCK -> OBJBLOCK [1:18]
    |--LCURLY -> { [1:18]
    |--METHOD_DEF -> METHOD_DEF [7:4]
    |   |--MODIFIERS -> MODIFIERS [7:4]
    |   |--TYPE -> TYPE [7:4]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [3:4]
    |   |   |   |--COMMENT_CONTENT -> *\n     *\n     * @param ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ\n      [3:6]
    |   |   |   `--BLOCK_COMMENT_END -> */ [6:5]
    |   |   `--LITERAL_VOID -> void [7:4]
    |   |--IDENT -> aᇭᇮᇯᇰᇱᇲᇳᇴᇵᇶᇷᇸᇹᇺ [7:9]
    |   |--LPAREN -> ( [7:24]
    |   |--PARAMETERS -> PARAMETERS [7:25]
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF [7:25]
    |   |       |--MODIFIERS -> MODIFIERS [7:25]
    |   |       |--TYPE -> TYPE [7:25]
    |   |       |   `--LITERAL_INT -> int [7:25]
    |   |       `--IDENT -> ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ [7:29]
    |   |--RPAREN -> ) [7:40]
    |   `--SLIST -> { [7:42]
    |       `--RCURLY -> } [7:43]
    `--RCURLY -> } [10:0]

 ➜  src java -jar checkstyle-9.0-SNAPSHOT-all.jar -J Test.java
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:5] Javadoc comment at column 15 has parse error. Details: no viable alternative at input 'ᇤ' while parsing JAVADOC_TAG
        at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:116)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:97)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:79)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:306)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)


```

We must update the documentation accordingly, as we cannot claim full unicode character support until we support it in both Javadoc and Java grammar.

**Comment by rnveach** [comment]
Can you create an issue on what is needed for Javadoc to support unicode?
