### ISSUE TITLE
TreeWalker initialization error. WILDCARD_TYPE not found.

### ISSUE THREAD

**Issue by dlopatin** [checkstyle/checkstyle#853]
After update Checkstyle Eclipse plugin to 6.4.0 get next error on every build:

	eclipse.buildId=4.4.2.M20150204-1700
	java.version=1.7.0_75
	java.vendor=Oracle Corporation
	BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
	Framework arguments:  -product org.eclipse.epp.package.jee.product
	Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

	net.sf.eclipsecs.core
	Error
	Thu Mar 26 16:57:58 MSK 2015
	Errors running builder 'Checkstyle Builder' on project 'ssel'.

	org.eclipse.core.runtime.CoreException: cannot initialize module TreeWalker - Token "WILDCARD_TYPE" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck@3fc53775
		at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
		at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:171)
		at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
		at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
		at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
		at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
		at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
		at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
		at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
		at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
		at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
		at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
		at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
	Caused by: net.sf.eclipsecs.core.util.CheckstylePluginException: cannot initialize module TreeWalker - Token "WILDCARD_TYPE" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck@3fc53775
		at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:66)
		at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:77)
		at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:166)
		at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:300)
		... 13 more
	Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "WILDCARD_TYPE" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck@3fc53775
		at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:184)
		at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:185)
		at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:310)
		at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:146)
		at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:142)
		... 14 more
	Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "WILDCARD_TYPE" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck@3fc53775
		at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:317)
		at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:192)
		at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:185)
		at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:163)
		... 18 more

Checked "WhitespaceAroundCheck" and didn't find any custom configuration.

**Comment by romani** [comment]
problem is not reproduced on latest eclipse4.4.2 , with latest eclipse-cs on internal Google config.

and ....

checktyle is console library all issues at this issue-tracker should be reproduced from CLI, eclipse integration is Eclipse-cs project - http://eclipse-cs.sourceforge.net/#!/ , if you have a problem with Eclipse-cs please report issue at http://sourceforge.net/p/eclipse-cs/bugs/ .

**Comment by dlopatin** [comment]
According to task "TreeWalker: Check.getAcceptableTokens() method is ignored" #342 and revision [Acceptable tokens are specified for all checks, issue #342](https://github.com/checkstyle/checkstyle/commit/abe2b200312ee72aa552026b1a34e8bd72bfdc4e#diff-97) `WILDCARD_TYPE` wasn't included to acceptable checks. Please confirm that it's correct.

**Comment by romani** [comment]
We need to extend that collection.

Next time please provide configuration to reproduce the failure from command line, how to run cli - "Download And Run" at http://checkstyle.sourceforge.net/cmdline.html

**Comment by dlopatin** [comment]
Ok, configuration to get error:

	<?xml version="1.0"?>
	<!DOCTYPE module PUBLIC
			  "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
			  "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

	<module name = "Checker">
		<property name="charset" value="UTF-8"/>

		<property name="severity" value="warning"/>
		
		<module name="FileTabCharacter">
			<property name="eachLine" value="true"/>
		</module>

		<module name="TreeWalker">
			<module name="WhitespaceAround">
				<property name="tokens" value="WILDCARD_TYPE"/>
			</module>
		</module>
	</module>

**Comment by romani** [comment]
You can simply change a code and do PR :) , it is 10 seconds to fix issue.

**Comment by dlopatin** [comment]
Yes, but perhaps there are some more tokens wasn't included to acceptable ones for this and other checks. I think it would be useful to review all of them. So, this task could be more global.

**Comment by romani** [comment]
We have about 200 Checks, do you have time to do detailed analysis ? I already spent  significat amout of time to review , and i missed that. Who else will do that with better diligence ? :) 

If you do not have answers to these question, we just need to fix a simple mistake.

**Comment by dlopatin** [comment]
No one. Made small fix.

**Comment by romani** [comment]
fixed, will be released in 6.5 (that weekends)

**Comment by romani** [comment]
@dlopatin , welcome back to checkstyle contributors.

**Comment by dlopatin** [comment]
Thanks,
If you need help, feel free to ask me.

**Comment by romani** [comment]
we have 90 issues to resolve , choose any unassigned issue .

**Comment by BKShalini** [comment]
Hi,

I still get the same error mentioned above, 
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module Checker - cannot initialize module TreeWalker - Token "WILDCARD_TYPE" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck@2e128581
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:184)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:185)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:84)
	... 35 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "WILDCARD_TYPE" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck@2e128581
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:184)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:185)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:163)
	... 37 more

Here are the steps that i have performed.

1. Installed Checktyle plugin.
2. Have updated the quality gate to use the quality profile with this checkstyle and findbugs.
3. I have kept the checkstyle settings under Settings-Java empty

When I run teh sonar analysis it fails with the above mentioned error.
Can you please help?

Thanks
Shalini

**Comment by romani** [comment]
@BKShalini ,
fix was released at version 6.5 , Sonar checkstyle plugin http://docs.sonarqube.org/display/PLUG/Checkstyle+Plugin should be version 2.4 (that based on checkstyle 6.12.1)

**Comment by BKShalini** [comment]
Hi,

I have installed the version 3.44 still get this error - is this also
related to the version of maven.

Thanks
Shalini

**Comment by romani** [comment]
What is 3.44 ?

**Comment by BKShalini** [comment]
Check style plugin version is shown as 3.44 in Jenkins

**Comment by BKShalini** [comment]
Sorry i am on 2.3 i will update to 2.4 and try it.. Sorry for the mistake..

**Comment by BKShalini** [comment]
Thank you for the reply. It worked. . Thanks for your timely help

Regards
Shalini
