### ISSUE TITLE
update example of AST for TokenTypes.PARAMETERS

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#9551]
https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#PARAMETERS

needs to be extended to show example of AST.
Source to be updated: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

PLEASE READ for more details: https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-AST-in-TokenTypes

**Comment by Whitroy** [comment]
I am on it

**Comment by Whitroy** [comment]
Done #9551

![Capture1](https://user-images.githubusercontent.com/55481516/113011732-b2c0c880-9197-11eb-9157-fe45829483bd.PNG)

![Capture](https://user-images.githubusercontent.com/55481516/113011754-b9e7d680-9197-11eb-8f4d-90456b343316.PNG)

**Comment by Venkatesh-24** [comment]
I'm on it.

**Comment by AbhinavRajputEXE** [comment]
Hey, @romani @pbludov I did not make any modification in the code in any file, I just freshly cloned it and it's still showing me these many errors, is this normal? should I make changes that I need to make for this issue and ignore these warnings?
BTW errors are caused by this JavaLanguageLexer file, it says `cannot resolve symbol JavaLanguageLexer`
![Screenshot (405)](https://user-images.githubusercontent.com/80591258/141353525-02c7eb30-07d4-4e82-a365-e33e7f490898.png)

**Comment by Venkatesh-24** [comment]
@AbhinavRajputEXE I am also working on it I too got the same error and dont know what to do. 5 days back it didnt show any error but from yesterday its showing this error.

**Comment by pbludov** [comment]
You need to generate the parser code. `mvn clean compile` should fix it.
